run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
        - govet